# Generated by Django 2.2 on 2019-11-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf', models.CharField(max_length=15)),
                ('birth', models.DateField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
